### PR TITLE
update:search page can not work well

### PR DESCRIPTION
**Pull request by Just2**
1. update search page without login
2. claw all the field except for comment,repost and praise, because in search page most of these fields are few, and claw these should be login, I think it is meaningless.

### CODE REVIEW

**Comment by thekingofcity** [comment]
Thank for your PR!
In order to be merged, we would like to know:
1. Is the current uid part Lines:54-59 not work? If so, just remove it.
2. Why is ```weibo_img_path``` and ```weibo_video``` unimplemented?
3. What's the suggested search task rate for ip got not banned without login?

**Comment by Just2** [comment]
Hi,
1. I have removed them.
2. I have restored the codes for weibo_img_path and weibo_video
3. emmm, as a newbee, I could not give you some useful suggestions.
Thanks for you review

**Comment by thekingofcity** [comment]
Great, just one more thing before merge.
It would be nice if you return None instead of insert NULL when we deal with mid at Line:57, will be merged as quickly as possible after that.

**Comment by thekingofcity** [comment]
If there is no further update in 7 days, we will merge and update it :)

**Comment by Just2** [comment]
Sorry, I missed your reply 7days ago, Now the code has beed updated. thx

**Comment by thekingofcity** [comment]
Very thanks to your pull request and wish you a happy New year :)

**Pull request merged**
